# Generated by Django 3.2 on 2021-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='https://lh3.googleusercontent.com/proxy/cuQIyc55-Qqrt1jUMsX2voShiNleMLpr2J9D7yuj3XsnCV76j3XhXj629erLqZCW_pfQehZGAB5djuE0NMZPjyRdHRwfaZYNZVAmVf2y9Rm-n6MuhYrfb1nBIK4HCPKJtlxAhOzdIEvBVEwKZvo1AeXe4jPPQN05C-N7fyU', upload_to='images/'),
        ),
    ]
