# Generated by Django 3.2 on 2021-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210501_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='post-image/cat-image.jpeg', upload_to='images/'),
        ),
    ]
