# Generated by Django 3.2 on 2021-05-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='mysite\\mysite\\post_image\\cat-image.jpeg', upload_to='images/'),
        ),
    ]
