# Generated by Django 3.2 on 2021-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='https://i.stack.imgur.com/l60Hf.png', upload_to='images/'),
        ),
    ]
